stages:
  prepare:
    cmd: python src/prepare.py --out_dir data
    deps:
      - data/Pakistan_House_Price_Dataset.csv
      - src/prepare.py
    outs:
      - data/cleaned_data.csv
    params:
      - prepare.random_seed

  features:
    cmd: python src/features.py --in_csv data/cleaned_data.csv --out_dir data
    deps:
      - data/cleaned_data.csv
      - src/features.py
    outs:
      - data/X_train.npy
      - data/X_test.npy
      - data/y_train.npy
      - data/y_test.npy
      - models/model_features.pkl
      - models/label_encoders.pkl
      - models/feature_field_map.pkl
    params:
      - features.test_size
      - features.random_state

  train:
    cmd: python src/train.py --data_dir data --model_out model.pkl
    deps:
      - data/X_train.npy
      - data/y_train.npy
      - src/train.py
    outs:
      - model.pkl
      - models/house_price_model.pkl
    params:
      - train.n_estimators
      - train.max_depth
      - train.random_state

  evaluate:
    cmd: python src/evaluate.py --data_dir data --model model.pkl --out metrics/eval.json
    deps:
      - model.pkl
      - data/X_test.npy
      - data/y_test.npy
      - src/evaluate.py
    metrics:
      - metrics/eval.json:
          cache: false